//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_graphique.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibOperation")]
    public interface IVelibOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperation/GetVelibStations", ReplyAction="http://tempuri.org/IVelibOperation/GetVelibStationsResponse")]
        Client.ServiceReference1.Station[] GetVelibStations(Client.ServiceReference1.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperation/GetVelibStations", ReplyAction="http://tempuri.org/IVelibOperation/GetVelibStationsResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.Station[]> GetVelibStationsAsync(Client.ServiceReference1.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperation/GetCities", ReplyAction="http://tempuri.org/IVelibOperation/GetCitiesResponse")]
        Client.ServiceReference1.City[] GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibOperation/GetCities", ReplyAction="http://tempuri.org/IVelibOperation/GetCitiesResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.City[]> GetCitiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibOperationChannel : Client_graphique.ServiceReference1.IVelibOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibOperationClient : System.ServiceModel.ClientBase<Client_graphique.ServiceReference1.IVelibOperation>, Client_graphique.ServiceReference1.IVelibOperation {
        
        public VelibOperationClient() {
        }
        
        public VelibOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServiceReference1.Station[] GetVelibStations(Client.ServiceReference1.City city) {
            return base.Channel.GetVelibStations(city);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.Station[]> GetVelibStationsAsync(Client.ServiceReference1.City city) {
            return base.Channel.GetVelibStationsAsync(city);
        }
        
        public Client.ServiceReference1.City[] GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.City[]> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
    }
}
